# Generated by Django 5.0.6 on 2025-06-16 03:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
