# Generated by Django 5.0.6 on 2025-06-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_description_alter_module_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='module_photos/'),
        ),
    ]
