# Generated by Django 5.0.6 on 2025-06-15 11:52

import blogs.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[blogs.models.validate_title_length])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnails/', validators=[blogs.models.validate_image_extension])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='member.client')),
            ],
        ),
    ]
